# Temporary GitPage Host setup
title: CME192 MATLAB for Scientific Computing and Engineering
url: "https://stanford.edu"
baseurl: "/class/cme192"
repository: "john-winnicki/cme192-win26"


# Theme settings
doks:
    color_theme: blue
    header:
        logo:
            text: CME192
            image: true
        nav:
            - item_name: Schedule
              item_url: '/schedule/'
            - item_name: Lecture
              item_url: '/lecture'
            - item_name: Notes
              item_url: '/blog'
            - item_name: FAQ
              item_url: '/faq'
    footer:
        content:
            logo:
                text:
                image:
            copyright: Copyright &copy; 2020. - Stanford University <br>All rights reserved.
        social_list:
            # - network_name: facebook
            #   profile_url: '#'
            # - network_name: twitter
            #   profile_url: '#'
    google_analytics: UA-124237072-3
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
plugins_dir: ./_plugins
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md', 'scripts', 'vendor', 'vendor/bundle', '.bundle', 'Gemfile', 'Gemfile.lock', 'node_modules']
permalink: /:title/

# Course logistics
course:
    quarter: Winter 2026
    time: Thu 4:30 PM - 5:20 PM
    venue: Hewlett Teaching Center 102
    piazza: &pz 'https://piazza.com/class/k8jbpjv3nd3lk'
    canvas: 'https://canvas.stanford.edu'
    project_timeline:
        proposal: 2020-04-22T23:59:00-07:00
        milestone1: 2020-05-08T23:59:00-07:00
        milestone2: 2020-05-24T23:59:00-07:00
        poster_and_report: 2020-06-09T10:20:00-07:00
        long_date_format: "%B %-d, %A %I:%M %p"
        syllabus_date_format: "%m/%d %A %I:%M %p"
    links:
        schedule:
            icon:
            content: Schedule
            url: '/schedule/'
            external_url: false
        syllabus-pdf:
            icon:
            content: Syllabus
            url: 'https://github.com/john-winnicki/cme192-win26/blob/main/CME192_Syllabus.pdf'
            external_url: true
        canvas:
            icon:
            content: Canvas
            url: 'https://canvas.stanford.edu/courses/218100'
            external_url: true
        github:
            icon:
            content: GitHub
            url: 'https://github.com/john-winnicki/cme192-win26'
            external_url: true
        past-projects:
            icon:
            content: Past Projects
            url: '/past-projects'
            external_url: false
        project-2018-win:
            icon:
            content: Winter 2018
            url: '/past-projects/#winter-2018'
            external_url: false
        project-2018-spr:
            icon:
            content: Spring 2018
            url: '/past-projects/#spring-2018'
            external_url: false
        project-2018-fall:
            icon:
            content: Fall 2018
            url: '/past-projects/#fall-2018'
            external_url: false
        project-2019-win:
            icon:
            content: Winter 2019
            url: '/past-projects/#winter-2019'
            external_url: false
        project-2019-spr:
            icon:
            content: Spring 2019
            url: '/past-projects/#spring-2019'
            external_url: false
        project-2019-fall:
            icon:
            content: Fall 2019
            url: '/past-projects/#fall-2019'
            external_url: false
        project-2020-win:
            icon:
            content: Winter 2020
            url: '/past-projects/#winter-2020'
            external_url: false
        video2018:
            icon:
            content: Github
            url: 'https://github.com/john-winnicki/cme192-win26'
            external_url: true
        piazza:
            icon:
            content: Piazza
            url: *pz
            external_url: true
        video:
            icon:
            content: Canvas
            url: 'https://canvas.stanford.edu/courses/218100'
            external_url: true
    staff:
        - name: John Winnicki
          type: Instructor
          url: https://www.linkedin.com/in/johnwinnicki
          image: JohnWinnicki.jpg
    ta: []
